name: Build and Test GitHub Access

on:
  pull_request:
  merge_group:
  push:
    branches-ignore:
      - gh-pages
    paths:
      - functions/pom.xml
      - functions/github-access/**

jobs:
  build-and-test-github-access:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: 'Set up JDK'
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: 11
          cache: 'maven'
      - name: test
        run: |
          pushd functions/groovy-executor
          ../../mvnw -B -V package
