name: Build and Test Groovy Executor

on:
  pull_request:
  merge_group:
  push:
    branches-ignore:
      - gh-pages
    paths:
      - functions/pom.xml
      - functions/groovy-executor/**

jobs:
  build-and-test-executors:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        variant: ['groovy_3_0', 'groovy_2_5', 'groovy_4_0']
    steps:
      - uses: actions/checkout@v4
      - name: 'Set up JDK'
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: 11
          cache: 'maven'
      - name: test
        run: |
          pushd functions/groovy-executor
          ../../mvnw -B -V package -P ${{ matrix.variant }}
