name: Build Frontend

on:
  pull_request:
  merge_group:
  push:
    branches-ignore:
      - gh-pages
    paths:
      - services/frontend/**

jobs:
  build-and-test-frontend:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          # sync with deploy-frontend version
          node-version: '18.x'
      - run: cd services/frontend && npm ci
      - run: cd services/frontend && npm run build
      - run: cd services/frontend && npm run lint
      - run: cd services/frontend && npm run ci
