name: Deploy list_runtimes function

on:
  workflow_dispatch:

jobs:
  deploy-function-list-runtimes:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up Cloud SDK
        uses: google-github-actions/setup-gcloud@v1
        with:
          project_id: ${{ secrets.GCP_PROJECT_ID }}
          service_account_key: ${{ secrets.GCP_CREDENTIALS }}
          export_default_credentials: true
      - run: gcloud functions deploy list_runtimes --entry-point listRuntimes --trigger-http --runtime nodejs14 --allow-unauthenticated --memory 8192MB --region europe-west1 --source functions/list_runtimes --service-account list-function-groovy-runtimes@gwc-experiment.iam.gserviceaccount.com
